/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ZenVh {
    }
}
declare global {
    interface HTMLZenVhElement extends Components.ZenVh, HTMLStencilElement {
    }
    var HTMLZenVhElement: {
        prototype: HTMLZenVhElement;
        new (): HTMLZenVhElement;
    };
    interface HTMLElementTagNameMap {
        "zen-vh": HTMLZenVhElement;
    }
}
declare namespace LocalJSX {
    interface ZenVh {
    }
    interface IntrinsicElements {
        "zen-vh": ZenVh;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "zen-vh": LocalJSX.ZenVh & JSXBase.HTMLAttributes<HTMLZenVhElement>;
        }
    }
}
